//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteExampleLI.EmailWSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailWSReference.EmailWSSoap")]
    public interface EmailWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento templateId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendRequestEmail", ReplyAction="*")]
        WebSiteExampleLI.EmailWSReference.SendRequestEmailResponse SendRequestEmail(WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendRequestEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<WebSiteExampleLI.EmailWSReference.SendRequestEmailResponse> SendRequestEmailAsync(WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento templateId del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotificationEmail", ReplyAction="*")]
        WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponse SendNotificationEmail(WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotificationEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponse> SendNotificationEmailAsync(WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequestEmail", Namespace="http://tempuri.org/", Order=0)]
        public WebSiteExampleLI.EmailWSReference.SendRequestEmailRequestBody Body;
        
        public SendRequestEmailRequest() {
        }
        
        public SendRequestEmailRequest(WebSiteExampleLI.EmailWSReference.SendRequestEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendRequestEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int estId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string templateId;
        
        public SendRequestEmailRequestBody() {
        }
        
        public SendRequestEmailRequestBody(int estId, string templateId) {
            this.estId = estId;
            this.templateId = templateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequestEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRequestEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebSiteExampleLI.EmailWSReference.SendRequestEmailResponseBody Body;
        
        public SendRequestEmailResponse() {
        }
        
        public SendRequestEmailResponse(WebSiteExampleLI.EmailWSReference.SendRequestEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendRequestEmailResponseBody {
        
        public SendRequestEmailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNotificationEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNotificationEmail", Namespace="http://tempuri.org/", Order=0)]
        public WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequestBody Body;
        
        public SendNotificationEmailRequest() {
        }
        
        public SendNotificationEmailRequest(WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNotificationEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string templateId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string studentEmail;
        
        public SendNotificationEmailRequestBody() {
        }
        
        public SendNotificationEmailRequestBody(string templateId, string studentEmail) {
            this.templateId = templateId;
            this.studentEmail = studentEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNotificationEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNotificationEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponseBody Body;
        
        public SendNotificationEmailResponse() {
        }
        
        public SendNotificationEmailResponse(WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendNotificationEmailResponseBody {
        
        public SendNotificationEmailResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmailWSSoapChannel : WebSiteExampleLI.EmailWSReference.EmailWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailWSSoapClient : System.ServiceModel.ClientBase<WebSiteExampleLI.EmailWSReference.EmailWSSoap>, WebSiteExampleLI.EmailWSReference.EmailWSSoap {
        
        public EmailWSSoapClient() {
        }
        
        public EmailWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebSiteExampleLI.EmailWSReference.SendRequestEmailResponse WebSiteExampleLI.EmailWSReference.EmailWSSoap.SendRequestEmail(WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest request) {
            return base.Channel.SendRequestEmail(request);
        }
        
        public void SendRequestEmail(int estId, string templateId) {
            WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest inValue = new WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest();
            inValue.Body = new WebSiteExampleLI.EmailWSReference.SendRequestEmailRequestBody();
            inValue.Body.estId = estId;
            inValue.Body.templateId = templateId;
            WebSiteExampleLI.EmailWSReference.SendRequestEmailResponse retVal = ((WebSiteExampleLI.EmailWSReference.EmailWSSoap)(this)).SendRequestEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebSiteExampleLI.EmailWSReference.SendRequestEmailResponse> WebSiteExampleLI.EmailWSReference.EmailWSSoap.SendRequestEmailAsync(WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest request) {
            return base.Channel.SendRequestEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebSiteExampleLI.EmailWSReference.SendRequestEmailResponse> SendRequestEmailAsync(int estId, string templateId) {
            WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest inValue = new WebSiteExampleLI.EmailWSReference.SendRequestEmailRequest();
            inValue.Body = new WebSiteExampleLI.EmailWSReference.SendRequestEmailRequestBody();
            inValue.Body.estId = estId;
            inValue.Body.templateId = templateId;
            return ((WebSiteExampleLI.EmailWSReference.EmailWSSoap)(this)).SendRequestEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponse WebSiteExampleLI.EmailWSReference.EmailWSSoap.SendNotificationEmail(WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest request) {
            return base.Channel.SendNotificationEmail(request);
        }
        
        public void SendNotificationEmail(string templateId, string studentEmail) {
            WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest inValue = new WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest();
            inValue.Body = new WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequestBody();
            inValue.Body.templateId = templateId;
            inValue.Body.studentEmail = studentEmail;
            WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponse retVal = ((WebSiteExampleLI.EmailWSReference.EmailWSSoap)(this)).SendNotificationEmail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponse> WebSiteExampleLI.EmailWSReference.EmailWSSoap.SendNotificationEmailAsync(WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest request) {
            return base.Channel.SendNotificationEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebSiteExampleLI.EmailWSReference.SendNotificationEmailResponse> SendNotificationEmailAsync(string templateId, string studentEmail) {
            WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest inValue = new WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequest();
            inValue.Body = new WebSiteExampleLI.EmailWSReference.SendNotificationEmailRequestBody();
            inValue.Body.templateId = templateId;
            inValue.Body.studentEmail = studentEmail;
            return ((WebSiteExampleLI.EmailWSReference.EmailWSSoap)(this)).SendNotificationEmailAsync(inValue);
        }
    }
}
